### ISSUE TITLE
konflik pada file readme

### ISSUE THREAD

**Issue by irfanprmnaa** [irfanprmnaa/web_ci#2]
@gritday tolong di perbaiki
`# web_ci
website dengan menggunakan teknologi ci

tes123124124214
1. ini adalah line baru
<<<<<<< HEAD
2 tes line baru 
=======
2. ini adalah line baru
>>>>>>> ce08116e1e4b2872eb7de8e2f7608182130c0497
`

**Comment by gritday** [comment]
![appoinment](https://user-images.githubusercontent.com/13690364/29464778-24c6eb28-8461-11e7-90aa-8c4be0c32c6e.jpeg)
cobaan ieu solusina
